Repository chronosphereio/calyptia-cli, pull requests merged in 2023-02, with the labels that each got.

#304 cluster_objects: add preliminary support for cluster objects.
  cmd/calyptia/delete.go
  cmd/calyptia/delete_pipeline_cluster_object.go
  cmd/calyptia/get.go
  cmd/calyptia/get_cluster_objects.go
  cmd/calyptia/get_pipeline_cluster_objects.go
  cmd/calyptia/update.go
  cmd/calyptia/update_pipeline_cluster_object.go
Labels: enhancement, core-v2-logging

#310 Dep update
  .github/workflows/ci.yml
  go.mod
  go.sum
Labels: dependencies, go, github_actions, cli

#300 Moves keyring stuffs to a package to save data locally
  cmd/calyptia/auth.go
  cmd/calyptia/config_token.go
  cmd/calyptia/config_url.go
  cmd/calyptia/main.go
  localdata/keyring.go
  localdata/keyring_test.go
Labels: enhancement, go, cli

#323 Add the flag skip-servic-creation to the aws and gcp commands
  aws/client.go
  cmd/calyptia/create_core_instance_aws.go
  cmd/calyptia/create_core_instance_gcp.go
  gcp/config.go
Labels: enhancement, go
